
# generated by: jx gitops variables
export APP_NAME="nodey554"
export BRANCH_NAME="master"
export DOCKERFILE_PATH="Dockerfile"
export DOCKER_REGISTRY="ghcr.io"
export DOCKER_REGISTRY_ORG="jstrachan"
export JX_CHART_REPOSITORY="http://jenkins-x-chartmuseum:8080"
export MINK_AS="tekton-bot"
export MINK_IMAGE="ghcr.io/jstrachan/nodey554:2.0.1300-dev"
export PIPELINE_KIND="release"
export REPO_NAME="nodey554"
export REPO_OWNER="jstrachan"
export VERSION="2.0.1300-dev"


# content from git...

# generated by: jx gitops variables
export APP_NAME="nodey554"
export BRANCH_NAME="master"
export DOCKERFILE_PATH="Dockerfile"
export DOCKER_REGISTRY="gcr.io"
export DOCKER_REGISTRY_ORG="jenkins-x-labs-bdd"
export JX_CHART_REPOSITORY="http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080"
export MINK_AS="tekton-bot"
export MINK_IMAGE="gcr.io/jenkins-x-labs-bdd/nodey554:2.0.1300-dev"
export PIPELINE_KIND="release"
export REPO_NAME="nodey554"
export REPO_OWNER="jstrachan"
export VERSION="2.0.1300-dev"


