apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  annotations:
    mythingy: edam
  creationTimestamp: null
  name: release
spec:
  pipelineSpec:
    tasks:
    - name: from-build-pack
      resources: {}
      taskSpec:
        metadata: {}
        stepTemplate:
          image: uses:jstrachan/jx3-pipeline-catalog/tasks/javascript/release.yaml@versionStream
          name: ""
          resources:
            requests:
              cpu: 400m
              memory: 512Mi
          volumeMounts:
          - mountPath: /builder/home/.npmrc
            name: npmrc
          workingDir: /workspace/source
        steps:
        - image: uses:jstrachan/jx3-pipeline-catalog/tasks/git-clone/git-clone.yaml@db314b741b376ac90ec5e2ef877efd0bc9d51c97
          name: ""
          resources: {}
        - name: next-version
          resources: {}
        - image: gcr.io/jenkinsxio/jx-gitops:0.0.0-SNAPSHOT-PR-469-1
          name: jx-variables
          resources: {}
          script: |
            #!/usr/bin/env sh
            jx gitops variables
        - name: build-npm-install
          resources: {}
        - name: build-npm-test
          resources: {}
        - name: build-container-build
          resources: {}
        - name: promote-changelog
          resources: {}
        - name: promote-helm-release
          resources: {}
        - name: promote-jx-promote
          resources: {}
        volumes:
        - name: npmrc
          secret:
            optional: true
            secretName: npmrc
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 240h0m0s
status: {}
